# Generated by Django 3.0.8 on 2020-12-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201201_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='FL14.jpg', null=True, upload_to='blog/'),
        ),
    ]
